# Generated by Django 3.1.1 on 2020-09-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ZVLJCYTG', 'ZVLJCYTG'), ('AC4ICZFM', 'AC4ICZFM'), ('2PKFJHPY', '2PKFJHPY'), ('GF2GY8ZF', 'GF2GY8ZF'), ('XH4Z5946', 'XH4Z5946')], max_length=9)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
