# Generated by Django 3.1.1 on 2020-09-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_promotionlog_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionlog',
            name='winner',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
