# Generated by Django 3.1.1 on 2020-09-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_auto_20200920_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionlog',
            name='winner',
        ),
        migrations.AddField(
            model_name='promotionlog',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'won'), (0, 'lost')], null=True),
        ),
    ]
